name = "ping-target-reminder"
main = "workers/reminder/index.ts"
compatibility_date = "2026-10-05"

[vars]
REMINDER_ENDPOINT = "https://ping-target.vercel.app/api/cron/target-reminder"

[triggers]
crons = ["* * * * *"]
